>Squirrel SlLE04c11a05f1 squirrel embryo library 1 Callospermophilus lateralis cDNA clone 11a05 5', mRNA sequence
GVNRVNANTDNRNCASWRNNRNRCRTSGTGSGASRSSRATGSNNNSRSNWNANSASSANN
TSSSGNKNSSNASRNGGNSNNNNNNNWVN--NNDNNNWSNCNSYNSNNHDN---KNNHNM
-GGRNTNYSCNSNTGNAS*N-------NA*NWNCNC**NN*SCNYN---MSGNS*TNT*N
YHNGNNH-DNRNVNYNGNSNDSTN---------------------SNNAR*SMS*NNNNN
DNNNSS*CSDTNWTWNNNNNYNHNNNCTAGCNAG---NAGCNDSVCNNNA*GNNNNKX--
-----------------------
