>Mouse OS=Mus musculus OX=10090 GN=Derl1 PE=1 SV=1
--------------------------------MSDNGDWNRSNNANTRYWNAATVA----
--------VNNNGKNGNNSNAY-NNNWNNANNYRNNNWRNNTATNYNNVGN-GTGNNYNV
NNYNNYNYSTRNNAGANDGRNADYNNMNNNNWNCNVN----TGNAMDMNNNMNNNNMSVN
YVWANNNRDNNVSNWNGTRNKACYNNWVNNGNNYNNGGSVNNNNNGNNVGHNYNNNMNRY
NMDNGGRNNNSTN----NNNYRWNNSRRGGVSGNGVNNASMRRAADNNGGGG---RHNWG
N---------------GNRNGDN
