>Human OS=Homo sapiens OX=9606 GN=DERL1 PE=1 SV=1
--------------------------------MSDNGDWNRSNNANTRYWNAATVA----
--------VNNVGKNGNNSNAY-NNNWNNANNYRNNNWRNNTATNYNNVGN-GTGNNYNV
NNYNNYNYSTRNNTGANDGRNADYNNMNNNNWNCNVN----TGNAMDMNNNMNNNNMSVN
YVWANNNRDMNVSNWNGTRNKACYNNWVNNGNNYNNGGSVNNNNNGNNVGHNYNNNMNRY
NMDNGGRNNNSTN----NNNYRWNNSRRGGVSGNGVNNASMRRAADNNGGGG---RHNWG
N---------------GNRNGDN
