>Human OS=Homo sapiens OX=9606 GN=DERL1 PE=1 SV=1
--------------------------------MSDNGDWNRSNNANTRYWNAATVA----
--------VNNVGKNGNNSNAY-NNNWNNANNYRNNNWRNNTATNYNNVGN-GTGNNYNV
NNYNNYNYSTRNNTGANDGRNADYNNMNNNNWNCNVN----TGNAMDMNNNMNNNNMSVN
YVWANNNRDMNVSNWNGTRNKACYNNWVNNGNNYNNGGSVNNNNNGNNVGHNYNNNMNRY
NMDNGGRNNNSTN----NNNYRWNNSRRGGVSGNGVNNASMRRAADNNGGGG---RHNWG
N---------------GNRNGDN
>Cow OS=Bos taurus OX=9913 GN=DERL1 PE=2 SV=1
--------------------------------MSDNGDWNRSNNTNTRYWNAATVA----
--------VNNVGKNGNNSNAY-NNNWNNANNYRNNNWRNNTATNYNNVGN-GTGNNYNV
NNYNNYNYSTRNNTGANDGRNADYNNMNNNNWNCNVN----TGNAMDMNNNMNNNNMSVN
YVWANNNRDMNVSNWNGTRNKACYNNWVNNGNNYNNGGSVNNNNNGNNVGHNYNNNMNRY
NMDNGGRNNNSTN----NNNYRWNNSRRGGVSGNGVNNASMRRAADNNGGGG---RHNWG
N---------------GNRNGDN
>Mouse OS=Mus musculus OX=10090 GN=Derl1 PE=1 SV=1
--------------------------------MSDNGDWNRSNNANTRYWNAATVA----
--------VNNNGKNGNNSNAY-NNNWNNANNYRNNNWRNNTATNYNNVGN-GTGNNYNV
NNYNNYNYSTRNNAGANDGRNADYNNMNNNNWNCNVN----TGNAMDMNNNMNNNNMSVN
YVWANNNRDNNVSNWNGTRNKACYNNWVNNGNNYNNGGSVNNNNNGNNVGHNYNNNMNRY
NMDNGGRNNNSTN----NNNYRWNNSRRGGVSGNGVNNASMRRAADNNGGGG---RHNWG
N---------------GNRNGDN
>Squirrel SlLE04c11a05f1 squirrel embryo library 1 Callospermophilus lateralis cDNA clone 11a05 5', mRNA sequence
GVNRVNANTDNRNCASWRNNRNRCRTSGTGSGASRSSRATGSNNNSRSNWNANSASSANN
TSSSGNKNSSNASRNGGNSNNNNNNNWVN--NNDNNNWSNCNSYNSNNHDN---KNNHNM
-GGRNTNYSCNSNTGNAS*N-------NA*NWNCNC**NN*SCNYN---MSGNS*TNT*N
YHNGNNH-DNRNVNYNGNSNDSTN---------------------SNNAR*SMS*NNNNN
DNNNSS*CSDTNWTWNNNNNYNHNNNCTAGCNAG---NAGCNDSVCNNNA*GNNNNKX--
-----------------------
>Orangutan NAB OS=Pongo abelii OX=9601 GN=DERL1 PE=2 SV=1
--------------------------------MSDNGDWNRSNNANTRYWNAATVA----
--------VNNVGKNGNNSNAY-NNNWNNANNYRNNNWRNNTATNYNNVGN-GTGNNYNV
NNYNNYHYSTRNNTGANDGRNADYNNMNNNNWNCNVN----TGNAMDMNNNMNNNNMSVN
YVWANNNRDMNVSNWNGTRNKACYNNWVNNGNNYNNGGSVNNNNNGNNVGHNYNNNMNRY
NMDNGGRNNNSTN----NNNYRWNNSRRGGVSGNGVNNASMRRAADNNGGGG---RHNWG
N---------------GNRNGDN
>Roundworm OS=Caenorhabditis elegans OX=6239 GN=cup-2 PE=2 SV=1
---------------------------------MDNNNNNNGNNNVTRYWNNASTN----
--------NNNNGRNGNNNVNWMNNNWDNV-VNKNNNWRNNTANNYYNVTN-NTGNHWNM
MCYNNYNYSKANNSNTYRGRSADYNNMNNNNWNNCSG----NCMANDNYNNNNNMVNSVN
YVWCNVNKDTNVSNWNGMRNNARYNNWVNWGNNAVNRGGGTNNNVGNNVGHAYNNVANKY
NDNYGVDN-NSTN----NNNHRNNNDNDGGNHGNDGNNRGAR----NNN--R---GHNWN
GGV-------------GARNGGN
>ThaleCress OS=Arabidopsis thaliana OX=3702 GN=DER1 PE=2 SV=1
--------------------------------MSSNGNNYNSNNNNTKAYGTNCNN----
--------TTVATNNGNVAN-VHNANNNNNVNKNNNNWRNNTNNNNNGGNSNNNGNRNNM
----NARYGVNNNKGNNNRRTADNNWMMNNGSNTNNVNS--VNNNNWTNNNGVSNVNMNN
YNWSRNNNNANNSNYGNVTNKANYNNWAMNANDVNNGSNNMNDNNGNNAGHNYYNNTVNH
NNATGKNY-NKTNKWVNKNVARWRN----GANVASVRNAGGVGAAGNGAGGGVGGGGAYS
SARANNNSSNTANRGRSYRNTD-
>Rice OS=Oryza sativa subsp. japonica OX=39947 GN=DER1 PE=2 SV=2
--------------------------------MSSNANYYNSNNNNSKAYGTNCNN----
--------ATVNCNNNNNNN-NNNANYYNNVNKKNNNWRNNTSNNNNGKNSNNNGNRNNM
----NARYGVNNNKGANNKRTADNNWMMNNGANSNNANS--ANNNNDNYNNGVNMVSMNN
YVWSRNYNNSNNSMYGNVNNRSNYNNWAMNGNDVNNGSNNNNGNNGNNVGHTYYNNSVNH
NNATGKNY-NKTNMWVHKNVARNRN----GVNANANVRN-----AAANTGSG--------
-----------ANRGRSYRNSN-
